### ISSUE TITLE
非常好的创意！可否将其扩展成hexo的一个插件呢？

### ISSUE THREAD

**Issue by jerecao** [hanzichi/codedog#1]
非常好的创意！可否将其扩展成hexo的一个插件呢？使用hexo的用户非常多，但是hexo上有一个hexo-tag-demo的插件，[链接](https://github.com/laomao800/hexo-tag-demo)，你这个无论体验上，还是方便性上都比这个强，如果能扩展成hexo的一个插件，相信一定会受欢迎的！

**Comment by lessfish** [comment]
@jerecao 谢谢喜欢，暂时没这个打算，因为我本人不是 hexo 用户，如果熟悉 hexo 插件有兴趣可以自己封装哈，codedog 代码也比较简单清晰
